[project]
name = "py-image-metadata-embedder"
version = "0.0.0"
description = "Embed metadata into image"
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "rjoydip", email = "joydipand@gmail.com"}
]
dependencies = [
    "piexif>=1.1.3",
    "pillow>=11.2.1",
    "tifffile>=2025.3.30",
]
[dependency-groups]
lint = [
    "pre-commit>=4.2.0",
    "pyright>=1.1.399",
    "ruff>=0.11.6",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# UV
[tool.uv]
upgrade = false
default-groups = "all"

# Ruff
[tool.ruff]
exclude = [
    ".git",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "dist",
    "site-packages",
    "venv",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
